# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-08 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 11, 26, 49, 903768, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
